kubernetes_deployments_flux_url: ssh://git@github.com/OpenSourceMargays/infrastructure.git
kubernetes_deployments_flux_branch: main
kubernetes_deployments_flux_github_ssh_private_key_path: ""
kubernetes_deployments_flux_environment_name: "developemnt"