apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: flux-system
spec:
  chart:
    spec:
      chart: grafana
      targetNamespace: kube-system
      storageNamespace: kube-system
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
      # version: 1.14.0
  interval: 1d
