- name: Add cilium chart repo
  kubernetes.core.helm_repository:
    name: cilium
    repo_url: "https://helm.cilium.io"

- name: Deploy Cilium chart using values files on target
  kubernetes.core.helm:
    name: cilium
    chart_ref: cilium/cilium
    chart_version: 1.15.3
    release_namespace: kube-system
    values: "{{ lookup('ansible.builtin.file', 'values.yaml') | from_yaml }}"

- name: Wait for cilium pods to be ready
  shell: cilium status --wait
