apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: grafana-repository
  namespace: flux-system
spec:
  interval: 7d
  url: https://prometheus-community.github.io/helm-charts
