terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
    talos = {
      source = "siderolabs/talos"
    }
    helm = {
      source = "hashicorp/helm"
    }
  }
}

locals {
  nodes = {
    for node in var.configuration.spec.nodes : node.name => node
  }
  controlplane_nodes = [
    for node in var.configuration.spec.nodes : node
    if node.role == "controlplane"
  ]
  worker_nodes = [
    for node in var.configuration.spec.nodes : node
    if node.role == "worker"
  ]
}

resource "proxmox_download_file" "talos_iso" {
  content_type = "iso"
  datastore_id = "truenas-nfs"
  node_name    = "minisforum"
  url          = var.configuration.spec.cluster.image
  file_name    = "talos.iso"
}

resource "proxmox_virtual_environment_vm" "talos" {
  for_each = local.nodes

  name      = each.value.name
  tags      = [each.value.role, "kubernetes", "talos"]
  node_name = "odroid01"

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_download_file.talos_iso.id
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = each.value.resources.disk
  }

  cpu {
    cores = each.value.resources.cpu
    type  = "host"
  }

  memory {
    dedicated = each.value.resources.memory
    floating  = each.value.resources.memory
  }

  network_device {
    bridge      = each.value.network.bridge
    mac_address = each.value.network.mac_address
    vlan_id     = each.value.network.vlan_id
  }

  initialization {
    ip_config {
      ipv4 {
        address = "dhcp"
      }
    }
  }

  serial_device {}

  # should be true if qemu agent is not installed / enabled on the VM
  stop_on_destroy = true
}

data "helm_template" "cilium" {
  namespace    = var.configuration.spec.helm.helm_release.namespace
  name         = var.configuration.spec.helm.helm_release.name
  repository   = var.configuration.spec.helm.helm_release.repository
  chart        = var.configuration.spec.helm.helm_release.chart
  version      = var.configuration.spec.helm.helm_release.version
  kube_version = trimprefix(var.configuration.spec.cluster.kubernetes_version, "v")

  values = [yamlencode(var.configuration.spec.helm.helm_release.values)]
}

resource "talos_machine_secrets" "this" {}

data "talos_machine_configuration" "this" {
  for_each = local.nodes

  cluster_name       = var.configuration.spec.name
  machine_type       = each.value.role
  cluster_endpoint   = var.configuration.spec.cluster.endpoint
  kubernetes_version = var.configuration.spec.cluster.kubernetes_version
  machine_secrets    = talos_machine_secrets.this.machine_secrets
}

data "talos_client_configuration" "this" {
  cluster_name         = var.configuration.spec.name
  client_configuration = talos_machine_secrets.this.client_configuration
  nodes                = [for node in var.configuration.spec.nodes : node.network.address]
}

resource "talos_machine_configuration_apply" "this" {
  for_each = local.nodes

  client_configuration        = talos_machine_secrets.this.client_configuration
  machine_configuration_input = data.talos_machine_configuration.this[each.key].machine_configuration
  node                        = each.value.network.address
  config_patches = [
    yamlencode({
      machine = {
        install = {
          disk = "/dev/vda"
        }
      }
    }),
    yamlencode({
      cluster = {
        network = {
          cni = {
            # Disable the default CNI as we will be using Cilium instead
            name = var.configuration.spec.cluster.network.cni.name
          }
        }
        proxy = {
          # Disable kube-proxy, Cilium will replace it too
          disabled = var.configuration.spec.cluster.network.proxy.disabled
        }
        inlineManifests = [
          {
            name = "cilium"
            contents = join("---\n", [
              data.helm_template.cilium.manifest, # YAML generated by Helm
            ])
          }
        ]
      }
    })
  ]
  depends_on = [proxmox_virtual_environment_vm.talos]
}

resource "talos_machine_bootstrap" "this" {
  node                 = local.controlplane_nodes[0].network.address
  client_configuration = talos_machine_secrets.this.client_configuration
  depends_on = [
    talos_machine_configuration_apply.this
  ]
}

resource "talos_cluster_kubeconfig" "this" {
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = local.controlplane_nodes[0].network.address
  depends_on = [
    talos_machine_bootstrap.this
  ]
}

output "kubeconfig" {
  value     = talos_cluster_kubeconfig.this.kubeconfig_raw
  sensitive = true
}

output "talosconfig" {
  value     = data.talos_client_configuration.this.talos_config
  sensitive = true
}
