terraform {
  required_providers {
    proxmox = {
      source = "bpg/proxmox"
    }
    talos = {
      source = "siderolabs/talos"
    }
    helm = {
      source = "hashicorp/helm"
    }
    flux = {
      source  = "fluxcd/flux"
      version = "1.9.3"
    }
  }
}

locals {
  nodes = {
    for node in var.configuration.spec.nodes : node.name => node
  }
  controlplane_nodes = [
    for node in var.configuration.spec.nodes : node
    if node.role == "controlplane"
  ]
  worker_nodes = [
    for node in var.configuration.spec.nodes : node
    if node.role == "worker"
  ]
}

resource "proxmox_download_file" "talos_iso" {
  content_type = "iso"
  datastore_id = "truenas-nfs"
  node_name    = "minisforum"
  url          = var.configuration.spec.cluster.image
  file_name    = "talos.iso"
}

resource "proxmox_virtual_environment_vm" "talos" {
  for_each = local.nodes

  name      = each.value.name
  tags      = [each.value.role, "kubernetes", "talos"]
  node_name = each.value.proxmox_node_name

  disk {
    datastore_id = "local-lvm"
    file_id      = proxmox_download_file.talos_iso.id
    interface    = "virtio0"
    iothread     = true
    discard      = "on"
    size         = each.value.resources.disk
  }

  cpu {
    cores = each.value.resources.cpu
    type  = "host"
  }

  memory {
    dedicated = each.value.resources.memory
    floating  = each.value.resources.memory
  }

  network_device {
    bridge      = each.value.network.bridge
    mac_address = each.value.network.mac_address
    vlan_id     = each.value.network.vlan_id
  }

  initialization {
    ip_config {
      ipv4 {
        address = each.value.network.address
        gateway = each.value.network.gateway
      }
    }
  }

  serial_device {}

  # should be true if qemu agent is not installed / enabled on the VM
  stop_on_destroy = true
}

data "helm_template" "this" {
  for_each     = { for manifest in var.configuration.spec.manifests : manifest.name => manifest if manifest.type == "helm" }
  namespace    = each.value.namespace
  name         = each.value.name
  repository   = each.value.repository
  chart        = each.value.chart
  version      = each.value.version
  kube_version = trimprefix(var.configuration.spec.cluster.kubernetes_version, "v")

  values = [yamlencode(each.value.values)]
}

resource "talos_machine_secrets" "this" {}

data "talos_machine_configuration" "this" {
  for_each = local.nodes

  cluster_name       = var.configuration.spec.name
  machine_type       = each.value.role
  cluster_endpoint   = var.configuration.spec.cluster.endpoint
  kubernetes_version = var.configuration.spec.cluster.kubernetes_version
  machine_secrets    = talos_machine_secrets.this.machine_secrets
}

data "talos_client_configuration" "this" {
  cluster_name         = var.configuration.spec.name
  client_configuration = talos_machine_secrets.this.client_configuration
  nodes                = [for node in var.configuration.spec.nodes : node.network.address]
}

locals {
  config_patches_directory = var.configuration.spec.config_patches_directory == null ? null : (
    startswith(var.configuration.spec.config_patches_directory, "/")
    ? var.configuration.spec.config_patches_directory
    : abspath("${path.root}/${var.configuration.spec.config_patches_directory}")
  )

  # Load config patches from the specified directory.
  # Relative paths are resolved from the root module directory.
  config_patches = local.config_patches_directory != null ? [
    for file in fileset(local.config_patches_directory, "*.yaml") : yamlencode(yamldecode(file("${local.config_patches_directory}/${file}")))
  ] : []
}

resource "talos_machine_configuration_apply" "this" {
  for_each = local.nodes

  client_configuration        = talos_machine_secrets.this.client_configuration
  machine_configuration_input = data.talos_machine_configuration.this[each.key].machine_configuration
  node                        = each.value.network.address
  config_patches = concat(
    [
      yamlencode({
        cluster = {
          inlineManifests = [
            for manifest in var.configuration.spec.manifests : {
              name = manifest.name
              contents = manifest.type == "helm" ? join("---\n", [
                data.helm_template.this[manifest.name].manifest, # YAML generated by Helm
              ]) : manifest.manifest
            } if manifest.phase == "bootstrap"
          ],
          extraManifests = [
            for manifest in var.configuration.spec.manifests : {
              name = manifest.name
              contents = manifest.type == "helm" ? join("---\n", [
                data.helm_template.this[manifest.name].manifest, # YAML generated by Helm
              ]) : manifest.manifest
            } if manifest.phase == "post-bootstrap"
          ]
        }
      })
    ],
    local.config_patches
  )
  depends_on = [proxmox_virtual_environment_vm.talos]
}

resource "talos_machine_bootstrap" "this" {
  node                 = local.controlplane_nodes[0].network.address
  client_configuration = talos_machine_secrets.this.client_configuration
  depends_on = [
    talos_machine_configuration_apply.this
  ]
}

resource "talos_cluster_kubeconfig" "this" {
  client_configuration = talos_machine_secrets.this.client_configuration
  node                 = local.controlplane_nodes[0].network.address
  depends_on = [
    talos_machine_bootstrap.this
  ]
}

data "talos_cluster_health" "this" {
  client_configuration   = talos_machine_secrets.this.client_configuration
  control_plane_nodes    = [for node in local.controlplane_nodes : node.network.address]
  worker_nodes           = [for node in local.worker_nodes : node.network.address]
  endpoints              = [local.controlplane_nodes[0].network.address]
  skip_kubernetes_checks = false

  timeouts = {
    read = "5m"
  }
  depends_on = [
    talos_cluster_kubeconfig.this
  ]
}

provider "flux" {
  kubernetes = {
    host                   = talos_cluster_kubeconfig.this.kubernetes_client_configuration.host
    client_certificate     = base64decode(talos_cluster_kubeconfig.this.kubernetes_client_configuration.client_certificate)
    client_key             = base64decode(talos_cluster_kubeconfig.this.kubernetes_client_configuration.client_key)
    cluster_ca_certificate = base64decode(talos_cluster_kubeconfig.this.kubernetes_client_configuration.ca_certificate)
  }
  git = {
    url = var.configuration.spec.flux.url
    ssh = {
      username    = var.configuration.spec.flux.username
      private_key = file(var.configuration.spec.flux.private_key_file)
    }
  }
}

resource "flux_bootstrap_git" "this" {
  depends_on = [data.talos_cluster_health.this]
  components_extra = [
    "image-reflector-controller",
    "image-automation-controller"
  ]
  embedded_manifests     = true
  kustomization_override = var.configuration.spec.flux.patch_file != null ? file(var.configuration.spec.flux.patch_file) : null
  path                   = var.configuration.spec.flux.path
}
