apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../base

patches:
  - target:
      kind: HelmRelease
      name: kube-prometheus-stack
    patch: |-
      - op: replace
        path: /spec/values/grafana/enabled
        value: true
      - op: replace
        path: /spec/values/prometheus/prometheusSpec/remoteWrite[0]/writeRelabelConfigs[0]/replacement
        value: monitoring
