apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: grafana-tempo
  namespace: monitoring
specs:
  - endpointSelector:
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: tempo
    ingress:
      - fromEndpoints:
          - matchLabels:
              io.cilium.k8s.policy.serviceaccount: tempo
        toPorts:
          - ports:
              - port: "7946"
                protocol: TCP
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "3100"
                protocol: TCP
    egress:
      - toEndpoints:
          - matchLabels:
              io.cilium.k8s.policy.serviceaccount: tempo
        toPorts:
          - ports:
              - port: "7946"
                protocol: TCP
  - nodeSelector:
      matchLabels: {}
    egress:
    - toEndpoints:
      - matchLabels:
          io.cilium.k8s.policy.serviceaccount: tempo
      toPorts:
      - ports:
        - port: '3100'
          protocol: TCP