- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - ethtool
      - iptables
      - nfs-common
    update_cache: true
    state: present
  tags:
    - packages
