apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: grafana
  namespace: monitoring
spec:
  chart:
    spec:
      chart: grafana
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
        namespace: flux-system
      version: 6.58.6
  values:
    sidecar:
      # alerts:
      #   enabled: true
      dashboards:
        enabled: true
        label: grafana_dashboard
        labelValue: "1"
        searchNamespace: ALL
      datasources:
        enabled: true
        label: grafana_datasource
        labelValue: "1"
      plugins:
       - grafana-github-datasource
  interval: 1h
