apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s-monitoring
  namespace: monitoring
spec:
  chart:
    spec:
      chart: k8s-monitoring
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
        namespace: flux-system
      version: 0.0.12
  values:
    cluster:
      name: home

    externalServices:
      prometheus:
        host: https://prometheus-prod-13-prod-us-east-0.grafana.net
        username: "1082786"
        password: "glc_eyJvIjoiODk2OTMyIiwibiI6ImdyYWZhbmEtYWdlbnQtYWdlbnQtdG9rZW4iLCJrIjoiOTJyN2VRQThBTjhFRDQzSGMyeDAyZHptIiwibSI6eyJyIjoidXMifX0="
      loki:
        host: https://logs-prod-006.grafana.net
        username: "642016"
        password: "glc_eyJvIjoiODk2OTMyIiwibiI6ImdyYWZhbmEtYWdlbnQtYWdlbnQtdG9rZW4iLCJrIjoiOTJyN2VRQThBTjhFRDQzSGMyeDAyZHptIiwibSI6eyJyIjoidXMifX0="

  interval: 1h
