apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: monitoring
spec:
  chart:
    spec:
      chart: loki
      sourceRef:
        kind: HelmRepository
        name: grafana-repository
        namespace: flux-system
      version: 5.9.2
  interval: 1h
  values:
    loki:
      # config: |
      #   auth_enabled: true
      # ingress:
      #   enabled: false
      # gateway: 
      #   enabled: true
      #   basicAuth:
      #     enabled: false
      storage:
        bucketNames:
          chunks: grafana-loki-chunks
          ruler: grafana-loki-ruler
          admin: grafana-loki-admin
        type: s3
        s3:
          s3: http://minio.minio.svc.cluster.local.:9000/
          # endpoint: http://minio.minio.svc:9000
          region: null
          secretAccessKey: margay12345
          accessKeyId: grafana
          s3ForcePathStyle: true
          insecure: true
      serviceMonitor:
        enabled: true