apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-repository
        namespace: flux-system
      version: 1.15.3
  valuesFrom:
    - kind: ConfigMap
      name: cilium-config
      valuesKey: main_values.yaml
    - kind: ConfigMap
      name: cilium-config
      valuesKey: monitoring_values.yaml
  interval: 1h
