apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  chart:
    spec:
      chart: cilium
      sourceRef:
        kind: HelmRepository
        name: cilium-repository
        namespace: flux-system
      version: 1.14.0
  values:
    kubeProxyReplacement: true
    k8sServiceHost: '192.168.1.101'
    k8sServicePort: 6443
    policyEnforcementMode: "default"
    # bgpControlPlane:
    #   enabled: true
    # gatewayAPI:
    #   enabled: true
    prometheus:
      enabled: true
    operator:
      prometheus:
        enabled: true
    hubble:
      enabled: true
      relay:
        enabled: true
        rollOutPods: true
      metrics:
        enabled:
          - dns:query;ignoreAAAA
          - drop
          - tcp
          - flow
          - icmp
          - http
  interval: 1h
