# External Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: mikrotik-snmp-exporter-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: mikrotik-snmp-exporter-auth
    creationPolicy: Owner
  data:
    - secretKey: SNMP_USERNAME
      remoteRef:
        key: mikrotik-snmp-v3
        property: username
    - secretKey: SNMP_AUTH_PASSWORD
      remoteRef:
        key: mikrotik-snmp-v3
        property: auth_password
    - secretKey: SNMP_PRIV_PASSWORD
      remoteRef:
        key: mikrotik-snmp-v3
        property: priv_password
