apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: minio
  namespace: minio
spec:
  interval: 5m
  chart:
    spec:
      chart: minio
      version: "5.0.14"
      sourceRef:
        kind: HelmRepository
        name: minio-repository
        namespace: flux-system
      interval: 1m
  values:
    resources:
      requests:
        memory: 1Gi
    replicas: 1
    persistence:
      enabled: false
    mode: standalone
    rootUser: rootuser
    rootPassword: rootpass123
    bucket:
    - name: grafana-tempo
      purge: false
      policy: none
