- name: Remove enterprise repositories
  ansible.builtin.file:
    path: "/etc/apt/sources.list.d/{{ item }}"
    state: absent
  with_items:
    - pve-enterprise.list
    - ceph.list

- name: Configure pve-no-subscription repository
  ansible.builtin.deb822_repository:
    name: pve-no-subscription
    types: [deb]
    uris: http://download.proxmox.com/debian/pve
    suites: ['{{ ansible_distribution_release }}']
    components:
      - pve-no-subscription
    state: present
    enabled: true
  tags:
    - apt

- name: Configure ceph-no-subscription repository
  ansible.builtin.deb822_repository:
    name: ceph
    types: [deb]
    uris: http://download.proxmox.com/debian/ceph-quincy
    suites: ['{{ ansible_distribution_release }}']
    components:
      - no-subscription
    state: present
    enabled: true
  tags:
    - apt
