apiVersion: opentelemetry.io/v1beta1
kind: OpenTelemetryCollector
metadata:
  name: opentelemetry-collector
spec:
  config:
    receivers:
      otlp:
        protocols:
          http:
            endpoint: 0.0.0.0:4318
    processors:
      memory_limiter:
        check_interval: 1s
        limit_percentage: 75
        spike_limit_percentage: 15

    exporters:
      otlphttp/traces:
        traces_endpoint: http://victoria-traces-cluster-vt-cluster-vtinsert.victoria-metrics.svc.cluster.local:10481/insert/0/opentelemetry/v1/traces
        encoding: proto
        compression: gzip
      otlphttp/metrics:
        metrics_endpoint: http://victoria-metrics-cluster-vminsert.victoria-metrics.svc.cluster.local:8480/insert/0/opentelemetry/v1/metrics
        encoding: proto
        compression: gzip
      otlphttp/logs:
        logs_endpoint: http://victoria-logs-cluster-vlinsert.victoria-metrics.svc.cluster.local:9481/insert/0/opentelemetry/v1/logs
        encoding: proto
        compression: gzip

    service:
      pipelines:
        traces:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlphttp/traces]
        metrics:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlphttp/metrics]
        logs:
          receivers: [otlp]
          processors: [memory_limiter]
          exporters: [otlphttp/logs]
