---
- name: Configure Kubernetes
  hosts: kube_control_plane[0]
  become: true
  roles:
    # - kubernetes/tools/helm
    # - kubernetes/tools/flux
    # - kubernetes/tools/ciliumcli
    - kubernetes/deployments/cilium
    # - kubernetes/deployments/flux
