---
- name: Configure Kubernetes
  hosts: kube_control_plane[0]
  become: true
  roles:
    - kubernetes/tools/helm
    - kubernetes/tools/flux
    - kubernetes/tools/ciliumcli

- name: Configure Kubernetes
  hosts: kube_control_plane[0]
  roles:
    - kubernetes/deployments/cilium
    # - kubernetes/deployments/flux
  vars:
    environment_name: "kind"
    branch_name: "main"
