---
- name: Configure Kubernetes
  hosts: k8s_cluster
  become: true
  tasks:
    - name: Fix permissions on /opt/cni/bin
      ansible.builtin.file:
        path: /opt/cni/bin
        owner: root
        group: root
        mode: '0o755'

- name: Configure Kubernetes
  hosts: kube_control_plane[0]
  become: true
  roles:
    - kubernetes/tools/helm
    - kubernetes/tools/flux
    - kubernetes/tools/ciliumcli

- name: Configure Kubernetes
  hosts: kube_control_plane[0]
  become: true
  roles:
    - kubernetes/deployments/cilium
    - kubernetes/deployments/flux
  vars:
    environment_name: "kind"
    branch_name: "main"
