apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: dragonfly
spec:
  chart:
    spec:
      chart: dragonfly
      sourceRef:
        kind: HelmRepository
        name: dragonfly-repository
      version: 1.7.6
  install:
    crds: CreateReplace
    remediation:
      retries: -1
  upgrade:
    crds: CreateReplace
    remediation:
      retries: -1
  values:
    manager:
      enable: true
      image:
        repository: dragonflyoss/manager
        tag: latest
      metrics:
        enable: true
    
    mysql:
      enable: true
    redis:
      enable: true
      
    scheduler:
      image:
        repository: dragonflyoss/scheduler
        tag: latest
      metrics:
        enable: true

    seedClient:
      image:
        repository: dragonflyoss/client
        tag: latest
      metrics:
        enable: true

    client:
      image:
        repository: dragonflyoss/client
        tag: latest
      metrics:
        enable: true
      config:
        host:
          # Specify the schedulerClusterID to distinguish different Dragonfly clusters.
          schedulerClusterID: 1
      dfinit:
        enable: false  # Talos does not support dfinit due to read-only root filesystem, so we disable it to avoid errors
  interval: 1h
