---
- name: Configure proxmox
  hosts: proxmox
  become: true
  roles:
  - proxmox/apt
  - proxmox/datacenter
  - proxmox/subscription_popup

- name: Setup nodes
  hosts: kubernetes
  become: true
  roles:
  - shutdown  # only when 'shutdown' tag provided
  - upgrade  # only when 'system_upgrade' tag provided
  - users
  - packages
  - tools
