# External Secret
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: apc-ups-snmp-exporter-auth
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: vault
    kind: ClusterSecretStore
  target:
    name: apc-ups-snmp-exporter-auth
    creationPolicy: Owner
  data:
    - secretKey: APC_SNMP_USERNAME
      remoteRef:
        key: apc-ups-snmpv3
        property: username
    - secretKey: APC_SNMP_AUTH_PASSWORD
      remoteRef:
        key: apc-ups-snmpv3
        property: auth_password
    - secretKey: APC_SNMP_PRIV_PASSWORD
      remoteRef:
        key: apc-ups-snmpv3
        property: priv_password
