apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: kagent-crds
spec:
  dependsOn:
    - name: kagent-crds
  chart:
    spec:
      chart: cert-manager
      sourceRef:
        kind: OCIRepository
        name: kagent-crds
      version: 0.9.12
  values:
    kgateway-agent:
      enabled: false
    istio-agent:
      enabled: false
    promql-agent:
      enabled: false
    observability-agent:
      enabled: false
    argo-rollouts-agent:
      enabled: false
  interval: 1h
