apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: flux-system
  namespace: flux-system
specs:
  - endpointSelector:
      matchLabels:
        io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
    ingress:
      # cert-manager-webhook -> kubelet
      - fromEntities:
          - remote-node
        toPorts:
          - ports:
              - port: "10250"
                protocol: TCP
      - fromEntities:
          - host
        toPorts:
          - ports:
              - port: "6080"
                protocol: TCP
  - nodeSelector:
      # apply to all nodes
      matchLabels: {}
    egress:
    # kubelet -> cert-manager-webhook
    - toEndpoints:
      - matchLabels:
          io.cilium.k8s.policy.serviceaccount: cert-manager-webhook
      toPorts:
      - ports:
        - port: '6080'
          protocol: TCP
