apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  name: flux-system
  namespace: flux-system
spec:
  endpointSelector: {}
  ingress:
    - fromEntities:
        - world
    - fromEndpoints:
        - {}
    - fromEntities:
        - cluster
  egress:
    - toEndpoints:
        - {}
    - toEntities:
        - cluster
    - toEntities:
        - world
