apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: external-secrets-controller
  namespace: flux-system
spec:
  interval: 30m
  retryInterval: 5m
  timeout: 5m
  path: ./flux/infrastructure/external-secrets/controller/overlays/monitoring
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system
