---
- name: Create directory for Kind configuration file
  ansible.builtin.file:
    path: "{{ kubernetes_kind_config_dir }}"
    state: directory

- name: Copy Kind configuration file
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "{{ kubernetes_kind_config_path }}"
  with_items:
    - "files/kind-config.yaml"

- name: Create Kind cluster
  ansible.builtin.shell: kind create cluster --name={{ kubernetes_kind_cluster_name }} --config={{ kubernetes_kind_config_path }}

- name: Check Kind cluster nodes
  ansible.builtin.shell: kind get nodes
