apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/storage/nfs/
  - ../base/victoria-stack/

patches:
  - target:
      kind: HelmRelease
      name: nfs-subdir-external-provisioner
    patch: |-
      - op: replace
        path: /spec/values/nfs/path
        value: /mnt/main/lab/clusters/monitoring
