- name: Remove subscription popup
  ansible.builtin.replace:
    path: "{{ proxmox_subscription_popup_lib_path }}"
    regexp: >-
      (^\s+)(Ext.Msg.show\(\{\s+title:\s+gettext\('No valid subscription'\))
    replace: '\1void({ //\2'
  notify: Restart pveproxy
  tags: proxmox_subscription_popup
