apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/minio
  - ../base/cilium
  # - ../base/open-telemetry
  - ../base/monitoring
  - ../base/storage/nfs

patches:
  - path: patches/cilium.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: cilium
  - path: patches/core-dns-network-policy.yaml
    target:
      group: cilium.io
      version: v2
      kind: CiliumNetworkPolicy
      name: core-dns
      namespace: kube-system
