apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../base/cert-manager
  - ../base/minio
  - ../base/cilium
  - ../base/open-telemetry
  - ../base/monitoring
  - ../base/storage/nfs

patches:
  - path: cilium-patch.yaml
    target:
      group: helm.toolkit.fluxcd.io
      version: v2beta1
      kind: HelmRelease
      name: cilium
