apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: kubelet
spec:
  nodeSelector:
    # apply to all nodes
    matchLabels: {}
  ingress:
  # api server -> kubelet
  - fromEntities:
    - kube-apiserver
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
  egress:
  # kubelet -> load balancer
  - toCIDR:
    - 192.168.1.101/32
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
