apiVersion: cilium.io/v2
kind: CiliumClusterwideNetworkPolicy
metadata:
  name: api-server
spec:
  nodeSelector:
    # apply to master nodes
    matchLabels:
      node-role.kubernetes.io/control-plane: ''
  ingress:
  # load balancer -> api server
  - fromCIDR:
    - 192.168.1.101/32
    toPorts:
    - ports:
      - port: '6443'
        protocol: TCP
  egress:
  # api server -> kubelet
  - toEntities:
    - remote-node
    toPorts:
    - ports:
      - port: '10250'
        protocol: TCP
