---
- name: Bootstrap FluxCD
  shell: |
    flux bootstrap git  \
      --url="{{ kubernetes_deployments_flux_url }}" \
      --private-key-file="{{ kubernetes_deployments_flux_github_ssh_private_key_path }}" \
      --branch="{{ kubernetes_deployments_flux_branch }}" \
      --path="flux/clusters/{{ kubernetes_deployments_flux_environment_name }}" \
      --network-policy=false \
      --silent
