apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: victoria-metrics-cluster
spec:
  chart:
    spec:
      chart: victoria-metrics-cluster
      sourceRef:
        kind: HelmRepository
        name: vm-repository
      version: 0.47.0
  values: {}
  interval: 1h
